# Generated by Django 4.0 on 2022-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=127, null=True)),
                ('category_en', models.CharField(blank=True, max_length=127, null=True)),
                ('category_az', models.CharField(blank=True, max_length=127, null=True)),
                ('category_ru', models.CharField(blank=True, max_length=127, null=True)),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('name_en', models.CharField(blank=True, max_length=127, null=True)),
                ('name_az', models.CharField(blank=True, max_length=127, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=127, null=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('author', models.CharField(blank=True, max_length=127, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', models.TextField(blank=True, help_text='Content', null=True)),
                ('content_en', models.TextField(blank=True, help_text='Content', null=True)),
                ('content_az', models.TextField(blank=True, help_text='Content', null=True)),
                ('content_ru', models.TextField(blank=True, help_text='Content', null=True)),
                ('author_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('created_at',),
            },
        ),
    ]
