# Generated by Django 4.0 on 2021-12-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('created_at',), 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='created_at',
        ),
    ]
