# Generated by Django 4.0 on 2022-02-16 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_az',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content', null=True),
        ),
    ]
