# Generated by Django 4.0 on 2022-03-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='blog',
            name='category_az',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_en',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory'),
        ),
    ]
