# Generated by Django 4.0 on 2022-02-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_content_alter_blog_content_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('slug', models.SlugField(blank=True, max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_az',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_en',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category_ru',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory'),
        ),
    ]
