# Generated by Django 4.0 on 2021-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_link_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
