# Generated by Django 4.0 on 2022-02-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_alter_blog_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('slug', models.SlugField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(blank=True, max_length=127, null=True, to='blog.BlogTag'),
        ),
    ]
