# Generated by Django 4.0 on 2022-02-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogtag_remove_blog_category_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
    ]
