# Generated by Django 4.0 on 2022-01-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_category_az_remove_blog_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_az',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_ru',
        ),
    ]
