# Generated by Django 4.0 on 2022-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_content_az_remove_blog_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category_az',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_en',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='category_ru',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_az',
            field=models.TextField(blank=True, help_text='Content', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=models.TextField(blank=True, help_text='Content', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_ru',
            field=models.TextField(blank=True, help_text='Content', null=True),
        ),
    ]
