# Generated by Django 4.0 on 2022-03-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homeslider_desc_az_homeslider_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='home/thumbnail/'),
        ),
    ]
