# Generated by Django 4.0 on 2022-03-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homeslider_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='thumbnail',
            field=models.ImageField(upload_to='home/thumbnail/'),
        ),
    ]
