# Generated by Django 4.0 on 2022-03-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceSlider',
        ),
    ]
