# Generated by Django 4.0 on 2022-03-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_service_serviceslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslider',
            name='desc_az',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceslider',
            name='desc_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceslider',
            name='title_az',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceslider',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
