# Generated by Django 4.0 on 2022-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=127, null=True)),
                ('category_en', models.CharField(blank=True, max_length=127, null=True)),
                ('category_az', models.CharField(blank=True, max_length=127, null=True)),
                ('category_ru', models.CharField(blank=True, max_length=127, null=True)),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('name_en', models.CharField(blank=True, max_length=127, null=True)),
                ('name_az', models.CharField(blank=True, max_length=127, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=127, null=True)),
                ('price1', models.SmallIntegerField(blank=True, null=True)),
                ('price2', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(upload_to='shop/')),
                ('slug', models.SlugField(blank=True, max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('created_at',),
            },
        ),
    ]
