# Generated by Django 4.0 on 2022-02-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='price1',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='price2',
        ),
    ]
