# Generated by Django 4.0 on 2022-01-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category_az',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='category_en',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='category_ru',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_az',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_en',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_ru',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
