# Generated by Django 4.0 on 2022-02-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
