# Generated by Django 4.0 on 2022-02-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcategory_alter_shop_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_az',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_en',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_ru',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
