# Generated by Django 4.0 on 2022-02-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_shop_category_alter_shop_category_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('slug', models.SlugField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_az',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_en',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_ru',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productcategory'),
        ),
    ]
