# Generated by Django 4.0 on 2022-02-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productcategory_alter_shop_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
