# Generated by Django 4.0 on 2022-02-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_az',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_en',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='category_ru',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
    ]
