# Generated by Django 4.0 on 2022-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_shop_category_alter_shop_category_az_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='shop',
            name='price2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
