# Generated by Django 4.0 on 2022-02-26 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_price_shop_price1_shop_price2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='brand',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
        migrations.AddField(
            model_name='shop',
            name='color',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
    ]
