# Generated by Django 4.0 on 2022-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
