# Generated by Django 4.0 on 2022-03-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_wishlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
