# Generated by Django 4.0 on 2022-03-01 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_wishlist_product_remove_wishlist_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='size',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
    ]
