# Generated by Django 4.0 on 2022-03-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_size_alter_shop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='size',
            field=models.CharField(blank=True, choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS'), ('XXS', 'XXS')], max_length=63, null=True),
        ),
    ]
