# Generated by Django 4.0 on 2022-03-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_shop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='size',
            field=models.ForeignKey(blank=True, max_length=127, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
    ]
