# Generated by Django 4.0 on 2022-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
