# Generated by Django 4.0 on 2022-03-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_shop_description_az_shop_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name_ru',
        ),
    ]
