# Generated by Django 4.0 on 2022-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_shop_category_ru_remove_shop_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='category_az',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name_az',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='name_en',
        ),
        migrations.AddField(
            model_name='shop',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
