# Generated by Django 4.0 on 2022-03-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_shop_category_az_remove_shop_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_en',
        ),
    ]
