# Generated by Django 4.0 on 2022-03-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_checkout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_az',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='name_en',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
