# Generated by Django 4.0 on 2022-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_shop_description_az_shop_description_en_shop_name_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='discounted_percent',
            field=models.IntegerField(default=0),
        ),
    ]
