# Generated by Django 4.0 on 2022-03-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_shop_discounted_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='discounted_percent',
            new_name='discount_percent',
        ),
    ]
