# Generated by Django 4.0 on 2021-12-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Social media icons')),
                ('name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Name')),
                ('specialty', models.CharField(blank=True, max_length=127, null=True, verbose_name='Name')),
            ],
        ),
    ]
