# Generated by Django 4.0 on 2021-12-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_about_icon_about_facebook_about_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('name', models.CharField(blank=True, max_length=127, null=True, verbose_name='Name')),
                ('specialty', models.CharField(blank=True, max_length=127, null=True, verbose_name='Speciality')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
