# Generated by Django 4.0 on 2021-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_leaders_delete_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaders',
            options={'ordering': ('created_at',), 'verbose_name': 'Leader', 'verbose_name_plural': 'Leader'},
        ),
        migrations.AddField(
            model_name='leaders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
