# Generated by Django 4.0 on 2021-12-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_leaders_options_leaders_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaders',
            options={'ordering': ('created_at',), 'verbose_name': 'Leader', 'verbose_name_plural': 'Leaders'},
        ),
    ]
